FROM tiangolo/uvicorn-gunicorn:python3.11-slim
LABEL author="Hemohespiikki of Hiihtoliitto"

COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt
COPY . /app
WORKDIR /app

