FROM python:3.11-slim
LABEL author="Hemohespiikki of Hiihtoliitto"

RUN apt update && apt install sqlite3
COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt
RUN mkdir -p /app/database
COPY initial_db.sqlite3 .
RUN sqlite3 /app/database/ski.db < initial_db.sqlite3
COPY . /app
WORKDIR /app
ENTRYPOINT [ "python3", "main.py" ]